apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: mysecret-sops
spec:
    secretTemplates:
        - name: my-secret
          stringData:
            PG_PASSWORD: ENC[AES256_GCM,data:XCi+5dYbcJu8gkjBDJM=,iv:I3rE65SnAdb2oZCReH74OnBWhIaXjs3/fhfSkrOzq/s=,tag:XNjlLqk2lo/H48uzSDGN6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19tfqxgdgx3fe96j8fyy0c65nsfj8ku8sl4ccfxnzpn3xpakylg5s8sgac7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArd2M2Um9NVVpQbStrNnY2
            cU9VakhUTG5udEUzc0o1R0RTMTlMK3BTQ21FCkRYaUlaaDRLTm00Z2o2UWV0NlJT
            R3d3bkNYVXdlbmZuSStRd0VmNHRiU2MKLS0tIEdDVTEvL2VCZklZTVpseXJaSjBF
            RSsrWTUzTlVsUHhIZ1lpMWQrQTRxdTQKexzpATkti3pcoF2dIB5QdyDPMSKCKy/x
            zSInhIlGa/69+gqAwcVF8yPc9OaJMFcQ5lyE00qCf/l5q0Lxw9IgZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-28T10:08:01Z"
    mac: ENC[AES256_GCM,data:9jLH/GpeH3ICZcV8kJ/upd9PINBQ8RLYC4fSLdtQFfrf9AKgpsS2OMkGgUWXAVhTo++VhvgnuKz79/9S4LNoT5vVZwksQasYFS53ThvfT2x86H27cIQxJmNp/cqheo+F0aUIfDZNKG5E6NMZbLid9lgO8DWCa2c4W3ddZ3b8s9g=,iv:aW2sLkUNjtke1h985B4nebwPa2nMvth2eB3IfhCWlO8=,tag:I0lDalhViBAeoSBG0T4QVg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
